# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.24.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.24.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/htr/Documents/develeop/cplus/QLumEditWasm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/htr/Documents/develeop/cplus/QLumEditWasm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.24.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.24.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/htr/Documents/develeop/cplus/QLumEditWasm/CMakeFiles /Users/htr/Documents/develeop/cplus/QLumEditWasm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/htr/Documents/develeop/cplus/QLumEditWasm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named QLumEdit

# Build rule for target.
QLumEdit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QLumEdit
.PHONY : QLumEdit

# fast build rule for target.
QLumEdit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/build
.PHONY : QLumEdit/fast

#=============================================================================
# Target rules for targets named QLumEdit_autogen

# Build rule for target.
QLumEdit_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QLumEdit_autogen
.PHONY : QLumEdit_autogen

# fast build rule for target.
QLumEdit_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit_autogen.dir/build.make CMakeFiles/QLumEdit_autogen.dir/build
.PHONY : QLumEdit_autogen/fast

QLumEdit_autogen/EXY53EAHJJ/qrc_application.o: QLumEdit_autogen/EXY53EAHJJ/qrc_application.cpp.o
.PHONY : QLumEdit_autogen/EXY53EAHJJ/qrc_application.o

# target to build an object file
QLumEdit_autogen/EXY53EAHJJ/qrc_application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/QLumEdit_autogen/EXY53EAHJJ/qrc_application.cpp.o
.PHONY : QLumEdit_autogen/EXY53EAHJJ/qrc_application.cpp.o

QLumEdit_autogen/EXY53EAHJJ/qrc_application.i: QLumEdit_autogen/EXY53EAHJJ/qrc_application.cpp.i
.PHONY : QLumEdit_autogen/EXY53EAHJJ/qrc_application.i

# target to preprocess a source file
QLumEdit_autogen/EXY53EAHJJ/qrc_application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/QLumEdit_autogen/EXY53EAHJJ/qrc_application.cpp.i
.PHONY : QLumEdit_autogen/EXY53EAHJJ/qrc_application.cpp.i

QLumEdit_autogen/EXY53EAHJJ/qrc_application.s: QLumEdit_autogen/EXY53EAHJJ/qrc_application.cpp.s
.PHONY : QLumEdit_autogen/EXY53EAHJJ/qrc_application.s

# target to generate assembly for a file
QLumEdit_autogen/EXY53EAHJJ/qrc_application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/QLumEdit_autogen/EXY53EAHJJ/qrc_application.cpp.s
.PHONY : QLumEdit_autogen/EXY53EAHJJ/qrc_application.cpp.s

QLumEdit_autogen/mocs_compilation.o: QLumEdit_autogen/mocs_compilation.cpp.o
.PHONY : QLumEdit_autogen/mocs_compilation.o

# target to build an object file
QLumEdit_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/QLumEdit_autogen/mocs_compilation.cpp.o
.PHONY : QLumEdit_autogen/mocs_compilation.cpp.o

QLumEdit_autogen/mocs_compilation.i: QLumEdit_autogen/mocs_compilation.cpp.i
.PHONY : QLumEdit_autogen/mocs_compilation.i

# target to preprocess a source file
QLumEdit_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/QLumEdit_autogen/mocs_compilation.cpp.i
.PHONY : QLumEdit_autogen/mocs_compilation.cpp.i

QLumEdit_autogen/mocs_compilation.s: QLumEdit_autogen/mocs_compilation.cpp.s
.PHONY : QLumEdit_autogen/mocs_compilation.s

# target to generate assembly for a file
QLumEdit_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/QLumEdit_autogen/mocs_compilation.cpp.s
.PHONY : QLumEdit_autogen/mocs_compilation.cpp.s

sources/configtabdialog.o: sources/configtabdialog.cpp.o
.PHONY : sources/configtabdialog.o

# target to build an object file
sources/configtabdialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/configtabdialog.cpp.o
.PHONY : sources/configtabdialog.cpp.o

sources/configtabdialog.i: sources/configtabdialog.cpp.i
.PHONY : sources/configtabdialog.i

# target to preprocess a source file
sources/configtabdialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/configtabdialog.cpp.i
.PHONY : sources/configtabdialog.cpp.i

sources/configtabdialog.s: sources/configtabdialog.cpp.s
.PHONY : sources/configtabdialog.s

# target to generate assembly for a file
sources/configtabdialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/configtabdialog.cpp.s
.PHONY : sources/configtabdialog.cpp.s

sources/eulumdat.o: sources/eulumdat.cpp.o
.PHONY : sources/eulumdat.o

# target to build an object file
sources/eulumdat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdat.cpp.o
.PHONY : sources/eulumdat.cpp.o

sources/eulumdat.i: sources/eulumdat.cpp.i
.PHONY : sources/eulumdat.i

# target to preprocess a source file
sources/eulumdat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdat.cpp.i
.PHONY : sources/eulumdat.cpp.i

sources/eulumdat.s: sources/eulumdat.cpp.s
.PHONY : sources/eulumdat.s

# target to generate assembly for a file
sources/eulumdat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdat.cpp.s
.PHONY : sources/eulumdat.cpp.s

sources/eulumdatcalculate.o: sources/eulumdatcalculate.cpp.o
.PHONY : sources/eulumdatcalculate.o

# target to build an object file
sources/eulumdatcalculate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatcalculate.cpp.o
.PHONY : sources/eulumdatcalculate.cpp.o

sources/eulumdatcalculate.i: sources/eulumdatcalculate.cpp.i
.PHONY : sources/eulumdatcalculate.i

# target to preprocess a source file
sources/eulumdatcalculate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatcalculate.cpp.i
.PHONY : sources/eulumdatcalculate.cpp.i

sources/eulumdatcalculate.s: sources/eulumdatcalculate.cpp.s
.PHONY : sources/eulumdatcalculate.s

# target to generate assembly for a file
sources/eulumdatcalculate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatcalculate.cpp.s
.PHONY : sources/eulumdatcalculate.cpp.s

sources/eulumdatimage.o: sources/eulumdatimage.cpp.o
.PHONY : sources/eulumdatimage.o

# target to build an object file
sources/eulumdatimage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatimage.cpp.o
.PHONY : sources/eulumdatimage.cpp.o

sources/eulumdatimage.i: sources/eulumdatimage.cpp.i
.PHONY : sources/eulumdatimage.i

# target to preprocess a source file
sources/eulumdatimage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatimage.cpp.i
.PHONY : sources/eulumdatimage.cpp.i

sources/eulumdatimage.s: sources/eulumdatimage.cpp.s
.PHONY : sources/eulumdatimage.s

# target to generate assembly for a file
sources/eulumdatimage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatimage.cpp.s
.PHONY : sources/eulumdatimage.cpp.s

sources/eulumdattablewidget.o: sources/eulumdattablewidget.cpp.o
.PHONY : sources/eulumdattablewidget.o

# target to build an object file
sources/eulumdattablewidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdattablewidget.cpp.o
.PHONY : sources/eulumdattablewidget.cpp.o

sources/eulumdattablewidget.i: sources/eulumdattablewidget.cpp.i
.PHONY : sources/eulumdattablewidget.i

# target to preprocess a source file
sources/eulumdattablewidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdattablewidget.cpp.i
.PHONY : sources/eulumdattablewidget.cpp.i

sources/eulumdattablewidget.s: sources/eulumdattablewidget.cpp.s
.PHONY : sources/eulumdattablewidget.s

# target to generate assembly for a file
sources/eulumdattablewidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdattablewidget.cpp.s
.PHONY : sources/eulumdattablewidget.cpp.s

sources/eulumdatwidget.o: sources/eulumdatwidget.cpp.o
.PHONY : sources/eulumdatwidget.o

# target to build an object file
sources/eulumdatwidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatwidget.cpp.o
.PHONY : sources/eulumdatwidget.cpp.o

sources/eulumdatwidget.i: sources/eulumdatwidget.cpp.i
.PHONY : sources/eulumdatwidget.i

# target to preprocess a source file
sources/eulumdatwidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatwidget.cpp.i
.PHONY : sources/eulumdatwidget.cpp.i

sources/eulumdatwidget.s: sources/eulumdatwidget.cpp.s
.PHONY : sources/eulumdatwidget.s

# target to generate assembly for a file
sources/eulumdatwidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatwidget.cpp.s
.PHONY : sources/eulumdatwidget.cpp.s

sources/eulumdatwidget2.o: sources/eulumdatwidget2.cpp.o
.PHONY : sources/eulumdatwidget2.o

# target to build an object file
sources/eulumdatwidget2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatwidget2.cpp.o
.PHONY : sources/eulumdatwidget2.cpp.o

sources/eulumdatwidget2.i: sources/eulumdatwidget2.cpp.i
.PHONY : sources/eulumdatwidget2.i

# target to preprocess a source file
sources/eulumdatwidget2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatwidget2.cpp.i
.PHONY : sources/eulumdatwidget2.cpp.i

sources/eulumdatwidget2.s: sources/eulumdatwidget2.cpp.s
.PHONY : sources/eulumdatwidget2.s

# target to generate assembly for a file
sources/eulumdatwidget2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatwidget2.cpp.s
.PHONY : sources/eulumdatwidget2.cpp.s

sources/eulumdatwidget3.o: sources/eulumdatwidget3.cpp.o
.PHONY : sources/eulumdatwidget3.o

# target to build an object file
sources/eulumdatwidget3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatwidget3.cpp.o
.PHONY : sources/eulumdatwidget3.cpp.o

sources/eulumdatwidget3.i: sources/eulumdatwidget3.cpp.i
.PHONY : sources/eulumdatwidget3.i

# target to preprocess a source file
sources/eulumdatwidget3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatwidget3.cpp.i
.PHONY : sources/eulumdatwidget3.cpp.i

sources/eulumdatwidget3.s: sources/eulumdatwidget3.cpp.s
.PHONY : sources/eulumdatwidget3.s

# target to generate assembly for a file
sources/eulumdatwidget3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatwidget3.cpp.s
.PHONY : sources/eulumdatwidget3.cpp.s

sources/eulumdatwidget4.o: sources/eulumdatwidget4.cpp.o
.PHONY : sources/eulumdatwidget4.o

# target to build an object file
sources/eulumdatwidget4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatwidget4.cpp.o
.PHONY : sources/eulumdatwidget4.cpp.o

sources/eulumdatwidget4.i: sources/eulumdatwidget4.cpp.i
.PHONY : sources/eulumdatwidget4.i

# target to preprocess a source file
sources/eulumdatwidget4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatwidget4.cpp.i
.PHONY : sources/eulumdatwidget4.cpp.i

sources/eulumdatwidget4.s: sources/eulumdatwidget4.cpp.s
.PHONY : sources/eulumdatwidget4.s

# target to generate assembly for a file
sources/eulumdatwidget4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/eulumdatwidget4.cpp.s
.PHONY : sources/eulumdatwidget4.cpp.s

sources/exportto.o: sources/exportto.cpp.o
.PHONY : sources/exportto.o

# target to build an object file
sources/exportto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/exportto.cpp.o
.PHONY : sources/exportto.cpp.o

sources/exportto.i: sources/exportto.cpp.i
.PHONY : sources/exportto.i

# target to preprocess a source file
sources/exportto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/exportto.cpp.i
.PHONY : sources/exportto.cpp.i

sources/exportto.s: sources/exportto.cpp.s
.PHONY : sources/exportto.s

# target to generate assembly for a file
sources/exportto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/exportto.cpp.s
.PHONY : sources/exportto.cpp.s

sources/main.o: sources/main.cpp.o
.PHONY : sources/main.o

# target to build an object file
sources/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/main.cpp.o
.PHONY : sources/main.cpp.o

sources/main.i: sources/main.cpp.i
.PHONY : sources/main.i

# target to preprocess a source file
sources/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/main.cpp.i
.PHONY : sources/main.cpp.i

sources/main.s: sources/main.cpp.s
.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/main.cpp.s
.PHONY : sources/main.cpp.s

sources/maintabwidget.o: sources/maintabwidget.cpp.o
.PHONY : sources/maintabwidget.o

# target to build an object file
sources/maintabwidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/maintabwidget.cpp.o
.PHONY : sources/maintabwidget.cpp.o

sources/maintabwidget.i: sources/maintabwidget.cpp.i
.PHONY : sources/maintabwidget.i

# target to preprocess a source file
sources/maintabwidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/maintabwidget.cpp.i
.PHONY : sources/maintabwidget.cpp.i

sources/maintabwidget.s: sources/maintabwidget.cpp.s
.PHONY : sources/maintabwidget.s

# target to generate assembly for a file
sources/maintabwidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/maintabwidget.cpp.s
.PHONY : sources/maintabwidget.cpp.s

sources/mainwindow.o: sources/mainwindow.cpp.o
.PHONY : sources/mainwindow.o

# target to build an object file
sources/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/mainwindow.cpp.o
.PHONY : sources/mainwindow.cpp.o

sources/mainwindow.i: sources/mainwindow.cpp.i
.PHONY : sources/mainwindow.i

# target to preprocess a source file
sources/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/mainwindow.cpp.i
.PHONY : sources/mainwindow.cpp.i

sources/mainwindow.s: sources/mainwindow.cpp.s
.PHONY : sources/mainwindow.s

# target to generate assembly for a file
sources/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/mainwindow.cpp.s
.PHONY : sources/mainwindow.cpp.s

sources/newdialog.o: sources/newdialog.cpp.o
.PHONY : sources/newdialog.o

# target to build an object file
sources/newdialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/newdialog.cpp.o
.PHONY : sources/newdialog.cpp.o

sources/newdialog.i: sources/newdialog.cpp.i
.PHONY : sources/newdialog.i

# target to preprocess a source file
sources/newdialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/newdialog.cpp.i
.PHONY : sources/newdialog.cpp.i

sources/newdialog.s: sources/newdialog.cpp.s
.PHONY : sources/newdialog.s

# target to generate assembly for a file
sources/newdialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/newdialog.cpp.s
.PHONY : sources/newdialog.cpp.s

sources/renderwidget.o: sources/renderwidget.cpp.o
.PHONY : sources/renderwidget.o

# target to build an object file
sources/renderwidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/renderwidget.cpp.o
.PHONY : sources/renderwidget.cpp.o

sources/renderwidget.i: sources/renderwidget.cpp.i
.PHONY : sources/renderwidget.i

# target to preprocess a source file
sources/renderwidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/renderwidget.cpp.i
.PHONY : sources/renderwidget.cpp.i

sources/renderwidget.s: sources/renderwidget.cpp.s
.PHONY : sources/renderwidget.s

# target to generate assembly for a file
sources/renderwidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/renderwidget.cpp.s
.PHONY : sources/renderwidget.cpp.s

sources/validator.o: sources/validator.cpp.o
.PHONY : sources/validator.o

# target to build an object file
sources/validator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/validator.cpp.o
.PHONY : sources/validator.cpp.o

sources/validator.i: sources/validator.cpp.i
.PHONY : sources/validator.i

# target to preprocess a source file
sources/validator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/validator.cpp.i
.PHONY : sources/validator.cpp.i

sources/validator.s: sources/validator.cpp.s
.PHONY : sources/validator.s

# target to generate assembly for a file
sources/validator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/validator.cpp.s
.PHONY : sources/validator.cpp.s

sources/vars.o: sources/vars.cpp.o
.PHONY : sources/vars.o

# target to build an object file
sources/vars.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/vars.cpp.o
.PHONY : sources/vars.cpp.o

sources/vars.i: sources/vars.cpp.i
.PHONY : sources/vars.i

# target to preprocess a source file
sources/vars.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/vars.cpp.i
.PHONY : sources/vars.cpp.i

sources/vars.s: sources/vars.cpp.s
.PHONY : sources/vars.s

# target to generate assembly for a file
sources/vars.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QLumEdit.dir/build.make CMakeFiles/QLumEdit.dir/sources/vars.cpp.s
.PHONY : sources/vars.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... QLumEdit_autogen"
	@echo "... QLumEdit"
	@echo "... QLumEdit_autogen/EXY53EAHJJ/qrc_application.o"
	@echo "... QLumEdit_autogen/EXY53EAHJJ/qrc_application.i"
	@echo "... QLumEdit_autogen/EXY53EAHJJ/qrc_application.s"
	@echo "... QLumEdit_autogen/mocs_compilation.o"
	@echo "... QLumEdit_autogen/mocs_compilation.i"
	@echo "... QLumEdit_autogen/mocs_compilation.s"
	@echo "... sources/configtabdialog.o"
	@echo "... sources/configtabdialog.i"
	@echo "... sources/configtabdialog.s"
	@echo "... sources/eulumdat.o"
	@echo "... sources/eulumdat.i"
	@echo "... sources/eulumdat.s"
	@echo "... sources/eulumdatcalculate.o"
	@echo "... sources/eulumdatcalculate.i"
	@echo "... sources/eulumdatcalculate.s"
	@echo "... sources/eulumdatimage.o"
	@echo "... sources/eulumdatimage.i"
	@echo "... sources/eulumdatimage.s"
	@echo "... sources/eulumdattablewidget.o"
	@echo "... sources/eulumdattablewidget.i"
	@echo "... sources/eulumdattablewidget.s"
	@echo "... sources/eulumdatwidget.o"
	@echo "... sources/eulumdatwidget.i"
	@echo "... sources/eulumdatwidget.s"
	@echo "... sources/eulumdatwidget2.o"
	@echo "... sources/eulumdatwidget2.i"
	@echo "... sources/eulumdatwidget2.s"
	@echo "... sources/eulumdatwidget3.o"
	@echo "... sources/eulumdatwidget3.i"
	@echo "... sources/eulumdatwidget3.s"
	@echo "... sources/eulumdatwidget4.o"
	@echo "... sources/eulumdatwidget4.i"
	@echo "... sources/eulumdatwidget4.s"
	@echo "... sources/exportto.o"
	@echo "... sources/exportto.i"
	@echo "... sources/exportto.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
	@echo "... sources/maintabwidget.o"
	@echo "... sources/maintabwidget.i"
	@echo "... sources/maintabwidget.s"
	@echo "... sources/mainwindow.o"
	@echo "... sources/mainwindow.i"
	@echo "... sources/mainwindow.s"
	@echo "... sources/newdialog.o"
	@echo "... sources/newdialog.i"
	@echo "... sources/newdialog.s"
	@echo "... sources/renderwidget.o"
	@echo "... sources/renderwidget.i"
	@echo "... sources/renderwidget.s"
	@echo "... sources/validator.o"
	@echo "... sources/validator.i"
	@echo "... sources/validator.s"
	@echo "... sources/vars.o"
	@echo "... sources/vars.i"
	@echo "... sources/vars.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

